default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: test
  password: test
  host: localhost
  timeout: 5000

# CREATE USER test WITH ENCRYPTED PASSWORD 'test';
# CREATE DATABASE potres2020_data_dev OWNER test;
development:
  database: potres2020_data_dev
  <<: *default

# CREATE USER test WITH ENCRYPTED PASSWORD 'test';
# CREATE DATABASE potres2020_data_test OWNER test;
# CREATE DATABASE potres2020_data_test_1 OWNER test;
# CREATE DATABASE potres2020_data_test_2 OWNER test;
# CREATE DATABASE potres2020_data_test_3 OWNER test;
# CREATE DATABASE potres2020_data_test_4 OWNER test;
test:
  database: potres2020_data_test
  <<: *default

production:
  database: potres2020_data_prod
  <<: *default
